# 演習問題

In [167]:
from glob import glob
import pandas as pd
import numpy as np
from scipy import stats  
import matplotlib.pyplot as plt
import japanize_matplotlib

In [168]:
files = glob("../csv/演習問題_データアナリティクス基礎/*")
for i, f in enumerate(files):
    print(i, f)

0 ../csv/演習問題_データアナリティクス基礎\第10章演習問題_乱数で発生させて分布の基本統計量.xlsx
1 ../csv/演習問題_データアナリティクス基礎\第2章演習問題_クレームデータ.xlsx
2 ../csv/演習問題_データアナリティクス基礎\第3章演習問題_職場ストレス.xlsx
3 ../csv/演習問題_データアナリティクス基礎\第4章演習問題_児童のネット利用時間.xlsx
4 ../csv/演習問題_データアナリティクス基礎\第5章演習問題_生鮮野菜の購入額.xlsx
5 ../csv/演習問題_データアナリティクス基礎\第7章演習問題_授業効果の検証.xlsx
6 ../csv/演習問題_データアナリティクス基礎\第8章演習問題1_健康食品・化粧品販売額.xlsx
7 ../csv/演習問題_データアナリティクス基礎\第8章演習問題2_百貨店の衣料品売上高.xlsx
8 ../csv/演習問題_データアナリティクス基礎\第9章演習問題_自由記述データ＆形態素解析データ.xlsx

In [169]:
df = pd.read_excel(files[0])
print(df.columns)
df.columns = [i for i in range(df.shape[1])]
df.info()
df

Index(['A', 'Unnamed: 1', 'B', 'Unnamed: 3', 'C', 'Unnamed: 5', 'D',
       'Unnamed: 7', 'E', 'Unnamed: 9'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       13 non-null     object
 1   1       13 non-null     float64
 2   2       13 non-null     object
 3   3       13 non-null     float64
 4   4       13 non-null     object
 5   5       13 non-null     float64
 6   6       13 non-null     object
 7   7       13 non-null     float64
 8   8       13 non-null     object
 9   9       13 non-null     float64
dtypes: float64(5), object(5)
memory usage: 1.2+ KB

,0,1,2,3,4,5,6,7,8,9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,平均,0.037031,平均,2.990000,平均,1.506623,平均,0.493000,平均,3.989000
2,標準誤差,0.030733,標準誤差,0.053896,標準誤差,0.027798,標準誤差,0.015818,標準誤差,0.028455
3,中央値 （メジアン）,0.045953,中央値 （メジアン）,3.000000,中央値 （メジアン）,1.530854,中央値 （メジアン）,0.000000,中央値 （メジアン）,4.000000
4,最頻値 （モード）,-0.639156,最頻値 （モード）,2.000000,最頻値 （モード）,0.682546,最頻値 （モード）,0.000000,最頻値 （モード）,4.000000
5,標準偏差,0.971857,標準偏差,1.704349,標準偏差,0.879058,標準偏差,0.500201,標準偏差,0.899827
6,分散,0.944506,分散,2.904805,分散,0.772743,分散,0.250201,分散,0.809689
7,尖度,-0.052112,尖度,-0.110282,尖度,-1.252043,尖度,-2.003224,尖度,-0.138894
8,歪度,-0.028677,歪度,0.447139,歪度,-0.005825,歪度,0.028045,歪度,-0.622671
9,範囲,6.443297,範囲,9.000000,範囲,2.997894,範囲,1.000000,範囲,4.000000
10,最小,-3.355090,最小,0.000000,最小,0.000549,最小,0.000000,最小,1.000000
11,最大,3.088207,最大,9.000000,最大,2.998444,最大,1.000000,最大,5.000000
12,合計,37.030678,合計,2990.000000,合計,1506.622852,合計,493.000000,合計,3989.000000
13,データの個数,1000.000000,データの個数,1000.000000,データの個数,1000.000000,データの個数,1000.000000,データの個数,1000.000000

乱数A : 標準偏差と分散が1となるのは、標準正規分布とポワソン分布であり、ポワソン分布は min, max = 0, 1 ので $X \sim N(0, \ 1)$

In [170]:
n = 1000
np.random.seed()
df = pd.DataFrame()
df = pd.concat([df, pd.DataFrame(stats.bernoulli.rvs(0.8, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.uniform.rvs(0, 10, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.poisson.rvs(1, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.norm.rvs(size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.binom.rvs(15, 0.5, size=n)).describe().T], axis=0)
df.index = ['bernoulli', 'uniform', 'poisson', 'norm', 'binom']
df

,count,mean,std,min,25%,50%,75%,max
bernoulli,1000.0,0.793000,0.405358,0.000000,1.000000,1.000000,1.000000,1.000000
uniform,1000.0,4.991109,2.929060,0.010058,2.433391,5.002609,7.629897,9.998819
poisson,1000.0,0.994000,1.018332,0.000000,0.000000,1.000000,2.000000,6.000000
norm,1000.0,0.017609,0.975320,-3.056977,-0.635472,-0.014506,0.698323,3.726334
binom,1000.0,7.557000,1.949500,2.000000,6.000000,8.000000,9.000000,13.000000

乱数B : 最小値 0, 中央値 3, より $\lambda = 3$ のポワソン分布

In [171]:
df = pd.DataFrame()
df = pd.concat([df, pd.DataFrame(stats.bernoulli.rvs(0.8, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.uniform.rvs(0, 15, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.poisson.rvs(3, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.norm.rvs(3, 5, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.binom.rvs(10, 0.5, size=n)).describe().T], axis=0)
df.index = ['bernoulli', 'uniform', 'poisson', 'norm', 'binom']
df

,count,mean,std,min,25%,50%,75%,max
bernoulli,1000.0,0.792000,0.406080,0.000000,1.000000,1.000000,1.000000,1.000000
uniform,1000.0,7.241176,4.257215,0.047758,3.502522,6.919735,10.771123,14.999086
poisson,1000.0,3.041000,1.711212,0.000000,2.000000,3.000000,4.000000,11.000000
norm,1000.0,2.857108,4.884357,-12.942045,-0.547611,2.765153,6.093068,19.160130
binom,1000.0,5.035000,1.610705,0.000000,4.000000,5.000000,6.000000,10.000000

乱数C : 最小値 ≒ 0, 最大値 ≒ 3, より $X \sim U(0, 3)$ の一様分布

In [172]:
df = pd.DataFrame()
df = pd.concat([df, pd.DataFrame(stats.bernoulli.rvs(0.3, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.uniform.rvs(0, 3, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.poisson.rvs(3, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.norm.rvs(4, 10, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.binom.rvs(5, 0.5, size=n)).describe().T], axis=0)
df.index = ['bernoulli', 'uniform', 'poisson', 'norm', 'binom']
df

,count,mean,std,min,25%,50%,75%,max
bernoulli,1000.0,0.290000,0.453989,0.000000,0.000000,0.000000,1.000000,1.000000
uniform,1000.0,1.496302,0.846275,0.000009,0.776170,1.482885,2.202051,2.996454
poisson,1000.0,2.927000,1.724136,0.000000,2.000000,3.000000,4.000000,11.000000
norm,1000.0,3.647126,10.135204,-26.991088,-3.119787,3.547521,10.664679,33.238814
binom,1000.0,2.592000,1.125523,0.000000,2.000000,3.000000,3.000000,5.000000

乱数D : min, max, range = 0, 1, 1 より $X \sim Be(0.5)$

In [173]:
df = pd.DataFrame()
df = pd.concat([df, pd.DataFrame(stats.bernoulli.rvs(0.5, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.uniform.rvs(0, 10, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.poisson.rvs(2, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.norm.rvs(0, 1, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.binom.rvs(12, 0.5, size=n)).describe().T], axis=0)
df.index = ['bernoulli', 'uniform', 'poisson', 'norm', 'binom']
df

,count,mean,std,min,25%,50%,75%,max
bernoulli,1000.0,0.486000,0.500054,0.000000,0.000000,0.000000,1.000000,1.000000
uniform,1000.0,4.879538,2.843899,0.015036,2.367053,4.832156,7.267848,9.996794
poisson,1000.0,1.959000,1.404739,0.000000,1.000000,2.000000,3.000000,7.000000
norm,1000.0,0.010043,1.039168,-3.416939,-0.689548,0.008537,0.712275,3.745520
binom,1000.0,6.031000,1.736967,0.000000,5.000000,6.000000,7.000000,11.000000

乱数E : min, max = 1, 5 より $X \sim b(5, 0.8)$

In [184]:
df = pd.DataFrame()
df = pd.concat([df, pd.DataFrame(stats.bernoulli.rvs(0.85, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.uniform.rvs(1, 3, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.poisson.rvs(1, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.norm.rvs(0, 1, size=n)).describe().T], axis=0)
df = pd.concat([df, pd.DataFrame(stats.binom.rvs(5, 0.8, size=n)).describe().T], axis=0)
df.index = ['bernoulli', 'uniform', 'poisson', 'norm', 'binom']
df

,count,mean,std,min,25%,50%,75%,max
bernoulli,1000.0,0.834000,0.372267,0.000000,1.000000,1.000000,1.000000,1.000000
uniform,1000.0,2.548491,0.885395,1.003667,1.725386,2.629621,3.299112,3.998657
poisson,1000.0,1.001000,1.014903,0.000000,0.000000,1.000000,2.000000,6.000000
norm,1000.0,0.037203,1.012709,-2.762534,-0.653684,0.035304,0.695245,3.736174
binom,1000.0,3.994000,0.889244,1.000000,3.000000,4.000000,5.000000,5.000000